server:
  port: 3333
spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/spring-cloud-samples/config-repo
#          uri: /home/zwei/github/spring-cloud/config
          uri: https://github.com/S3S3L/config.git
#          basedir: target/config